<?php

namespace JMooreWV\CrashTape\Reports;

use JMooreWV\CrashTape\Support\InternalLog;

defined( 'ABSPATH' ) || exit;

/**
 * Manages the support-package storage directory: direct web access
 * blocked where possible, unpredictable filenames, generated
 * inside wp-content/uploads since that's writable on ordinary hosting, but
 * never served directly; only through Timeline's authenticated download
 * action.
 */
class Storage {

	const SUBDIR = 'crashtape-packages';

	public static function dir() {
		$dir = self::raw_dir();

		if ( ! file_exists( $dir ) ) {
			wp_mkdir_p( $dir );
		}

		// This is a storage failure: the directory genuinely
		// couldn't be created/isn't writable (read-only uploads dir, disk
		// full, permissions). Builder::build() will still fail its own way
		// moments later (ZipArchive::open() against this path), but that's
		// a distinct, already-logged export_failure; this is the earlier,
		// more specific fact.
		if ( ! is_dir( $dir ) || ! wp_is_writable( $dir ) ) {
			InternalLog::record( InternalLog::STORAGE_FAILURE, "Package directory is missing or not writable: {$dir}" );
		}

		self::protect( $dir );

		return trailingslashit( $dir );
	}

	/**
	 * Path only; never creates the directory. Used by delete_all() so
	 * uninstalling doesn't recreate the very directory it's about to
	 * remove.
	 */
	private static function raw_dir() {
		$upload_dir = wp_upload_dir();

		return trailingslashit( $upload_dir['basedir'] ) . self::SUBDIR;
	}

	private static function protect( $dir ) {
		$htaccess = $dir . '/.htaccess';

		if ( ! file_exists( $htaccess ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			file_put_contents( $htaccess, "# Generated by CrashTape, do not remove.\nRequire all denied\n<IfModule !mod_authz_core.c>\nDeny from all\n</IfModule>\n" );
		}

		$index = $dir . '/index.php';

		if ( ! file_exists( $index ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			file_put_contents( $index, "<?php\n// Silence is golden.\n" );
		}
	}

	public static function unique_filename() {
		$date  = gmdate( 'Ymd' );
		$token = strtoupper( substr( wp_generate_password( 10, false, false ), 0, 5 ) );

		return sprintf( 'crashtape-case-%s-%s.zip', $date, $token );
	}

	/**
	 * Release-readiness checklist Priority 9 "package paths cannot be
	 * manipulated" / "path traversal attempts": every current caller
	 * already only ever passes a filename this plugin generated itself
	 * (Storage::unique_filename(), or a `Package` row this plugin wrote
	 * that value into), so this was never actively exploitable today --
	 * but path() itself had no defense of its own, entirely trusting
	 * every caller to stay careful forever. basename() makes the
	 * guarantee unconditional: whatever `$filename` contains, the result
	 * can never resolve outside this directory (a `../../wp-config.php`
	 * becomes just `wp-config.php`, safely contained here, not read from
	 * the real site root).
	 */
	public static function path( $filename ) {
		// basename() only recognizes the *current* platform's directory
		// separator (backslash is a plain character on Linux/Unix, where
		// this plugin actually runs); normalizing backslashes to forward
		// slashes first neutralizes a backslash-based traversal attempt
		// regardless of which platform PHP itself happens to be running
		// on, rather than relying on that platform-specific behavior to
		// already match whichever separator style an attacker tries.
		return self::dir() . basename( str_replace( '\\', '/', (string) $filename ) );
	}

	public static function delete( $filename ) {
		$path = self::path( $filename );

		if ( file_exists( $path ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			unlink( $path );
		}
	}

	/**
	 * Removes every package file plus the directory itself (uninstall.php
	 * only; this is a full, irreversible wipe, not routine cleanup).
	 */
	public static function delete_all() {
		$dir = self::raw_dir();

		if ( ! is_dir( $dir ) ) {
			return;
		}

		// glob()'s '*' doesn't match dotfiles, so .htaccess needs listing
		// by name alongside the package zips and index.php.
		$files   = (array) glob( trailingslashit( $dir ) . '*', GLOB_NOSORT );
		$files[] = trailingslashit( $dir ) . '.htaccess';

		foreach ( $files as $file ) {
			if ( is_file( $file ) ) {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
				unlink( $file );
			}
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir, WordPress.PHP.NoSilencedErrors.Discouraged
		@rmdir( rtrim( $dir, '/' ) );
	}
}
