<?php

namespace JMooreWV\CrashTape\Isolation;

defined( 'ABSPATH' ) || exit;

/**
 * Manages the optional MU conflict-isolation loader. WordPress loads
 * active plugins very early, and mu-plugins load before that loop runs;
 * so filtering which plugins load for one specific request requires a
 * component that lives in wp-content/mu-plugins/, not a normal plugin.
 * This class only manages that file's presence; the file itself
 * (mu_loader_source()) is fully self-contained vanilla PHP with no
 * dependency on this plugin's classes/autoloader, since none of that has
 * loaded yet at the point mu-plugins execute.
 *
 * Belongs under a separate crashtape-pro package once that packaging/
 * licensing infrastructure exists; living here for now since that
 * infrastructure hasn't been built.
 */
class Loader {

	const MU_FILENAME = 'crashtape-loader.php';
	const MARKER      = 'Generated by CrashTape, safe to delete at any time.';

	/**
	 * "Only ever touch a file we own" cuts both ways; uninstall() already
	 * refused to delete a file without our marker; install() must
	 * equally refuse to silently overwrite one. A prior
	 * version didn't check this, so a stray unrelated file happening to
	 * already sit at wp-content/mu-plugins/crashtape-loader.php (however
	 * unlikely) would have been clobbered without a trace.
	 */
	public static function install() {
		$dir  = self::mu_plugin_dir();
		$path = self::path();

		if ( file_exists( $path ) && ! self::is_ours( $path ) ) {
			return false;
		}

		if ( ! file_exists( $dir ) ) {
			wp_mkdir_p( $dir );
		}

		if ( ! wp_is_writable( $dir ) ) {
			return false;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		return false !== file_put_contents( $path, self::mu_loader_source() );
	}

	/**
	 * Removes itself when isolation support is disabled, where filesystem
	 * permissions allow; only ever removes a file that carries our own
	 * marker comment, never an arbitrary file that happens to have this
	 * name.
	 */
	public static function uninstall() {
		$path = self::path();

		if ( ! file_exists( $path ) ) {
			return true;
		}

		if ( ! self::is_ours( $path ) ) {
			return false;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
		return unlink( $path );
	}

	public static function is_installed() {
		$path = self::path();

		return file_exists( $path ) && self::is_ours( $path );
	}

	private static function is_ours( $path ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		$contents = file_get_contents( $path, false, null, 0, 4096 );

		return false !== strpos( (string) $contents, self::MARKER );
	}

	private static function mu_plugin_dir() {
		return defined( 'WPMU_PLUGIN_DIR' ) ? WPMU_PLUGIN_DIR : WP_CONTENT_DIR . '/mu-plugins';
	}

	private static function path() {
		return trailingslashit( self::mu_plugin_dir() ) . self::MU_FILENAME;
	}

	/**
	 * Every security requirement for this filter maps to one line here:
	 * - cryptographically signed state: hash_hmac() + hash_equals() (see
	 *   the note below on why this isn't wp_hash())
	 * - expires: get_transient()'s own TTL
	 * - never accepts arbitrary plugin paths from the request: the cookie
	 *   carries only an opaque token: the actual plugin list only ever
	 *   comes from a server-side transient, and the result is an
	 *   intersection with the real active list; this can only ever
	 *   subtract plugins, never add one that wasn't already really active
	 * - emergency bypass: the option check above everything else
	 * - fails open: every validation failure returns $plugins unchanged
	 * - preserves stored state: filtering a filter's return value never
	 *   writes to the database
	 * - never grants capabilities: no auth code of any kind
	 *
	 * Known limitation, found via real testing rather than reasoned out in
	 * advance: isolation only affects the one browser request that
	 * actually carries the signed cookie. A page load that triggers
	 * WordPress's own background loopback requests; most commonly
	 * spawn_cron() firing on almost every front-end hit; will still load
	 * every plugin normally for those uncookied internal requests, since
	 * they don't carry the browser's cookie jar. This isn't a bug to fix;
	 * it's an inherent property of a per-browser-request cookie mechanism,
	 * worth knowing so an isolation test's results aren't second-guessed
	 * over cron-triggered side effects that were never in scope.
	 */
	public static function mu_loader_source() {
		return <<<'PHP'
<?php
/**
 * CrashTape Conflict Isolation Loader
 *
 * Generated by CrashTape, safe to delete at any time.
 * Deleting this file immediately restores normal plugin loading; it does
 * not touch the site's stored active-plugins configuration in any way.
 *
 * @package CrashTape
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

if ( get_option( 'crashtape_isolation_bypass' ) ) {
	return;
}

// wp_hash()/wp_salt() live in wp-includes/pluggable.php, which WordPress
// does not load until AFTER the active-plugins list has already been read
// (wp-settings.php reads it via wp_get_active_and_valid_plugins() long
// before requiring pluggable.php); calling wp_hash() here is a fatal
// "Call to undefined function." AUTH_KEY/AUTH_SALT come from wp-config.php,
// already defined by this point, so this signs against those directly
// instead. If a site somehow doesn't define them, auth cookies and nonces
// are already broken sitewide; this fails open rather than fatal either way.
if ( ! defined( 'AUTH_KEY' ) || ! defined( 'AUTH_SALT' ) ) {
	return;
}

add_filter(
	'option_active_plugins',
	function ( $plugins ) {
		if ( ! is_array( $plugins ) || empty( $_COOKIE['crashtape_isolate'] ) ) {
			return $plugins;
		}

		$raw = $_COOKIE['crashtape_isolate'];

		if ( ! is_string( $raw ) || false === strpos( $raw, '.' ) ) {
			return $plugins;
		}

		list( $token, $signature ) = explode( '.', $raw, 2 );

		$expected = hash_hmac( 'sha256', 'crashtape-isolation|' . $token, AUTH_KEY . AUTH_SALT );

		if ( ! hash_equals( $expected, $signature ) ) {
			return $plugins;
		}

		$allowlist = get_transient( 'crashtape_isolation_' . $token );

		if ( ! is_array( $allowlist ) ) {
			return $plugins;
		}

		return array_values( array_intersect( $plugins, $allowlist ) );
	},
	PHP_INT_MAX
);
PHP;
	}
}
